### PR TITLE
change KLDCriterion to KLDPenalty

### PR DESCRIPTION
**Pull request by joeyhng**
Change KLDCriterion to KLDPenalty, similar idea to [nn.L1Penalty](https://github.com/torch/nn/blob/master/doc/simple.md#nn.L1Penalty). This results in cleaner code and remove the need for KLDCriterion.

### CODE REVIEW

**Comment by y0ast** [comment]
Thanks for the PR!

Where are the gradients of the KLDpenalty backpropagated?

**Comment by joeyhng** [comment]
It is backpropagated to the encoder, as defined [here](https://github.com/joeyhng/VAE-Torch/blob/f164b80d7fa5b20abf59b36f487b0724a1c056a7/main.lua#L32) in the model.

**Comment by y0ast** [comment]
Ah, nice, missed that. Looks like a solid improvement in code quality!

I'll run some experiments this weekend to verify correctness.

**Comment by y0ast** [comment]
Thanks! Works well and makes code look nicer.

**Pull request merged**
